export const STRINGS = {
  auth: {
    login: 'Login',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginButton: 'Sign In',
  },
  devices: {
    title: 'Device Fleet',
    eyebrow: 'Digital Signage Control',
    subtitle: 'Monitor live status, pair new screens, and open any device to manage playlist content.',
    pairButton: 'Pair Device',
    logoutButton: 'Logout',
    pairingCodePlaceholder: '4-digit pairing code',
    totalDevices: 'Total Devices',
    online: 'Online',
    offline: 'Offline',
    paired: 'Paired',
    loading: 'Loading devices...',
    errorLoad: 'Failed to load devices.',
    errorPair: 'Pairing failed. Please verify the code.',
    errorClipboard: 'Unable to copy code from browser clipboard.',
    detail: {
      piIdTitle: 'Raspberry Pi Link',
      piIdLabel: 'Pi ID (MAC address)',
      piIdPlaceholder: 'b8:27:eb:12:34:56',
      piIdSaveButton: 'Save',
      piIdSaving: 'Saving...',
      piIdInvalid: 'Enter a valid MAC address (e.g. b8:27:eb:12:34:56).',
      piIdSaveSuccess: 'Pi ID updated successfully.',
      piIdSaveFailed: 'Failed to save pi_id.',
      analyticsTitle: 'Visitor Analytics',
      analyticsTotalUniqueVisitors: 'Total Unique Visitors',
      analyticsTotalWatchTime: 'Total Watch Time',
      analyticsAverageWatchTime: 'Average Watch Time',
      analyticsReturningVisitors: 'Returning Visitors',
      analyticsOneTimeVisitors: 'One-Time Visitors',
      analyticsGenderTitle: 'Gender Split',
      analyticsAgeTitle: 'Age Groups',
      analyticsVisitTypeTitle: 'Visit Frequency',
      analyticsPerVisitorTitle: 'Per-Visitor Watch Time',
      analyticsEmptyPrompt: 'Link a Pi ID above to see visitor analytics for this device.',
      analyticsErrorLoad: 'Failed to load analytics.',
      analyticsVisitorIdColumn: 'Visitor',
      analyticsWatchTimeColumn: 'Watch Time',
      analyticsFirstSeenColumn: 'First Seen',
      analyticsVisitsColumn: 'Visits',
      analyticsNoAgeData: 'No age data recorded yet.',
      analyticsMale: 'Male',
      analyticsFemale: 'Female',
      analyticsUnknown: 'Unknown',
    },
  },
};
