export const STRINGS = {
  auth: {
    login: 'Login',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginButton: 'Sign In',
  },
  devices: {
    title: 'Device Fleet',
    eyebrow: 'Digital Signage Control',
    subtitle: 'Monitor live status, pair new screens, and open any device to manage playlist content.',
    pairButton: 'Pair Device',
    logoutButton: 'Logout',
    pairingCodePlaceholder: '4-digit pairing code',
    totalDevices: 'Total Devices',
    online: 'Online',
    offline: 'Offline',
    paired: 'Paired',
    loading: 'Loading devices...',
    errorLoad: 'Failed to load devices.',
    errorPair: 'Pairing failed. Please verify the code.',
    errorClipboard: 'Unable to copy code from browser clipboard.',
    detail: {
      piIdTitle: 'Raspberry Pi Link',
      piIdLabel: 'Pi ID (MAC address)',
      piIdPlaceholder: 'b8:27:eb:12:34:56',
      piIdSaveButton: 'Save',
      piIdInvalid: 'Enter a valid MAC address (e.g. b8:27:eb:12:34:56).',
      piIdSaveFailed: 'Failed to save pi_id.',
      analyticsTitle: 'Visitor Analytics',
      analyticsUniqueVisitors: 'Unique Visitors',
      analyticsTotalWatchTime: 'Total Watch Time',
      analyticsPerVisitorTitle: 'Per-Visitor Watch Time',
      analyticsEmptyPrompt: 'Link a Pi ID above to see visitor analytics for this device.',
      analyticsErrorLoad: 'Failed to load analytics.',
      analyticsVisitorIdColumn: 'Visitor',
      analyticsWatchTimeColumn: 'Watch Time',
      analyticsFirstSeenColumn: 'First Seen',
    },
  },
};
