server {
    listen 80;
    server_name spatiabox.alterside.io;

    client_max_body_size 0;

    root /var/www/spatiabox;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name spatiabox.alterside.io;

    client_max_body_size 0;

    root /var/www/spatiabox;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    ssl_certificate /etc/letsencrypt/live/spatiabox.alterside.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/spatiabox.alterside.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

